server.port: 8081
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security
    username: D_ADMIN
    password: B_D!slb29Vne$%
  jpa:
    #open-in-view: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 200
  #redis:
  #  lettuce.pool:
  #    max-active: 10
  #    max-idle: 10
  #    min-idle: 2